<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-7FHEVMK" ignored="0" name="Surefire test" tests="4" failures="4" timestamp="04 sep 2020 02:05:14 GMT" time="20.152" errors="0">
  <testcase name="dividir" time="3.228" classname="com.example.service.CalculateSimpleTest">
    <failure type="java.lang.AssertionError" message="expected [3] but found [Resultado: 3.0]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [Resultado: 3.0]
at com.example.service.CalculateSimpleTest.dividir(CalculateSimpleTest.java:122)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- dividir -->
  <testcase name="multiplicar" time="3.222" classname="com.example.service.CalculateSimpleTest">
    <failure type="java.lang.AssertionError" message="expected [25] but found [Resultado: 25]">
      <![CDATA[java.lang.AssertionError: expected [25] but found [Resultado: 25]
at com.example.service.CalculateSimpleTest.multiplicar(CalculateSimpleTest.java:101)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- multiplicar -->
  <testcase name="resta" time="3.22" classname="com.example.service.CalculateSimpleTest">
    <failure type="java.lang.AssertionError" message="expected [10] but found [Resultado: 10]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [Resultado: 10]
at com.example.service.CalculateSimpleTest.resta(CalculateSimpleTest.java:81)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- resta -->
  <testcase name="suma" time="3.203" classname="com.example.service.CalculateSimpleTest">
    <failure type="java.lang.AssertionError" message="expected [12] but found [Resultado: 12]">
      <![CDATA[java.lang.AssertionError: expected [12] but found [Resultado: 12]
at com.example.service.CalculateSimpleTest.suma(CalculateSimpleTest.java:61)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- suma -->
</testsuite> <!-- Surefire test -->
